version: '3.9'
services:
  # pg-primary:
  #   container_name: pg-primary
  #   ports:
  #     - 5432:5432
  #   image: bitnami/postgresql:latest
  #   environment:
  #     - PGDATA=/bitnami/postgresql/data
  #     - POSTGRESQL_USERNAME=postgres
  #     - POSTGRESQL_PASSWORD=postgres
  #     - POSTGRESQL_DATABASE=hw6
  #   volumes:
  #     - 'pg-primary_data:/bitnami/postgresql'
  #   restart: always
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U admin']
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: hw7
    volumes:
      - mongo-data:/data/db\
volumes:
  mongo-data:
    driver: local
