import { UserRole } from '@/enum/userRole.enum';
import * as bcrypt from 'bcryptjs';
const salt = bcrypt.genSaltSync(10);

export const USER_DATA = [
  {
    id: 1,
    googleId: null,
    firstName: 'andrei',
    lastName: 'sakalouski',
    email: 'andriksokol311@gmail.com',
    role: UserRole.Admin,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 2,
    googleId: null,
    firstName: 'ivan',
    lastName: 'fedorov',
    email: 'ivan@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 3,
    googleId: null,
    firstName: 'sasha',
    lastName: 'Svetlich',
    email: 'sasha@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 4,
    googleId: null,
    firstName: 'anton',
    lastName: 'Maevsi',
    email: 'anton@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 5,
    googleId: null,
    firstName: 'katay',
    lastName: 'horer',
    email: 'katay@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 6,
    googleId: null,
    firstName: 'user6',
    lastName: 'user6',
    email: 'aaa@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 7,
    googleId: null,
    firstName: 'user7',
    lastName: 'user7',
    email: 'bbb@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 8,
    googleId: null,
    firstName: 'user8',
    lastName: 'user8',
    email: 'ccc@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 9,
    googleId: null,
    firstName: 'user9',
    lastName: 'user9',
    email: 'ddd@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
  {
    id: 10,
    googleId: null,
    firstName: 'user10',
    lastName: 'user10',
    email: 'eee@gmail.com',
    role: UserRole.User,
    passwordHash: bcrypt.hashSync('123', salt),
  },
];
