import { v4 as uuidv4 } from 'uuid';

export const VINYL_DATA = [
  {
    id: 1,
    name: 'Unknown Pleasures',
    description: `Divided into the "Inside" and the "Outside" on vinyl, the Manchester band''s debut album is housed in a fine Peter Saville sleeve - but make sure you get a version with the embossed texture on the cover! There was a 40th anniversary edition released in 2019 on ruby red vinyl and the black and white cover reversed.`,
    authorName: 'Joy Division',
    price: 3,
    link: uuidv4(),
  },
  {
    id: 2,
    name: 'The Stone Roses',
    description: `First released as CD was starting to become the format of choice, there was something pleasingly retro about owning this on vinyl, mainly thanks to the distinctive John Squire artwork on the outer and inner sleeves. You may need to crank up your amp, though - it''s a long album and those grooves get a bit small (and therefore quieter).`,
    authorName: 'The Stone Roses',
    price: 4,
    link: uuidv4(),
  },
  {
    id: 3,
    name: `Sgt Pepper''s Lonely Hearts Club Band`,
    description: `Some say Revolver is the best one to get on vinyl, but the Pepper package is much, much better. From the ground-breaking cover, to Sir Peter Blake''s cardboard cut-out inserts, this is a meticulously-sequenced album, complete with a dog whistle and a "secret track" engraved into the end of side two. It''s worth paying a bit extra for the original mono edition, which is the only Beatles-approved version and still sounds incredible.`,
    authorName: 'The Beatles',
    price: 8,
    link: uuidv4(),
  },
  {
    id: 4,
    name: `Whatever People Say I Am, That''s What I''m Not`,
    description: `One of the best debut albums of the past 20 years is a perfect listen on vinyl. Side 1 opens with the classic View From The Afternoon, while the flip kicks off with the equally memorable Riot Van. The record label continues the theme of the album cover artwork as it features a photo of a full ashtray.`,
    authorName: 'Arctic Monkeys',
    price: 4.99,
    link: uuidv4(),
  },
  {
    id: 5,
    name: `Definitely Maybe`,
    description: `Remastered in 2014 for the album''s twentieth anniversary, this is the definitive Britpop statement, complete with a memorable piece of cover art. And don''t forget all those incredible tunes within the grooves. They''re not bad, either.`,
    authorName: 'Oasis',
    price: 5.99,
    link: uuidv4(),
  },
  {
    id: 6,
    name: `The Queen Is Dead`,
    description: `Morrissey and Marr paid homage to the 1960s in their songwriting, so listening to this landmark record on MP3 or CD is just plain wrong. Plus, on vinyl, you get the fantastic gatefold sleeve, featuring the full lyrics and Stephen Wright''s classic shot of the band outside Salford Lad''s Club.`,
    authorName: 'The Smiths',
    price: 6,
    link: uuidv4(),
  },
  {
    id: 7,
    name: `Dark Side Of The Moon`,
    description: `Another classic rock essential, revel in the Hipgnosis artwork and ponder on life''s mysteries as you flip the record over after The Great Gig In The Sky. Money remains one of the all-time greatest "Side Two, Track Ones".`,
    authorName: 'Pink Floyd',
    price: 4.99,
    link: uuidv4(),
  },
  {
    id: 8,
    name: `Elephant`,
    description: `Jack and Meg''s career-defining album, pressed across two nice vinyl discs. "No computers were used during the writing, recording, mixing or mastering of this record" declare the sleeve notes. But you''re reading this digitally, so you''ve gone and ruined it.`,
    authorName: 'The White Stripes',
    price: 5.99,
    link: uuidv4(),
  },
  {
    id: 9,
    name: `The Hounds Of Love`,
    description: `La Bush’s finest work, segmented into two side-long pieces: The Hounds Of Love and The Ninth Wave. Side one is the hits, side two is one of Kate’s more interesting sonic explorations.`,
    authorName: 'Kate Bush',
    price: 4.99,
    link: uuidv4(),
  },
  {
    id: 10,
    name: `Sticky Fingers`,
    description: `You need to get your hands on the version with an actual zip on the cover, mind you. That''s the only way you''ll get the full risqué effect of Andy Warhol''s cover art. The music''s not bad either. Includes Brown Sugar, Sister Morphine, Wild Horses and many more!`,
    authorName: 'The Rolling Stones',
    price: 10,
    link: uuidv4(),
  },
  {
    id: 11,
    name: `London Calling`,
    description: `Released in the dying days of the 1970s, this very un-punk rock-like double album starts with the incredible title track and careers over four eclectic sides. Original copies didn''t list the final track, Train In Vain, which must have been a nice surprise.`,
    authorName: 'The Clash',
    price: 10,
    link: uuidv4(),
  },
  {
    id: 12,
    name: `Low`,
    description: `Let''s face it, any Bowie on vinyl is great, but this ''77 classic looks fantastic and is divided into the "pop" side with tracks like Sound And Vision, and the "ambient" side, with Brian Eno''s synthy soundscapes. Ian Curtis of Joy Division had a copy of this and so should you.`,
    authorName: 'David Bowie',
    price: 4.99,
    link: uuidv4(),
  },
  {
    id: 13,
    name: `Led Zeppelin IV`,
    description: `The Zep''s fourth outing included the all-time classic guitar player''s anthem, Stairway To Heaven and is an essential addition to any classic rock collection. Plus, you can appreciate the baffling sleeve artwork much better.`,
    authorName: 'Led Zeppelin',
    price: 12,
    link: uuidv4(),
  },
  {
    id: 14,
    name: `Blonde On Blonde`,
    description: `More fold-out sleeve fun, as Dylan''s classic double album bears a huge quarter-length portrait of the man. Kicking off with the hilarious Rainy Day Women #12 & 35, the LP''s final side is taken up with the ambitious eleven-minute track Sad Eyed Lady Of The Lowlands.`,
    authorName: 'Bob Dylan',
    price: 4.99,
    link: uuidv4(),
  },
  {
    id: 15,
    name: `Paul''s Boutique`,
    description: `The hip hop trio seemed washed up following their controversial debut, Licensed To Ill, but this ambitious melange of samples proved they weren''t just a novelty band. The vinyl edition makes the most of the excellent sleeve photo with a fold-out cover.`,
    authorName: 'Beastie Boys',
    price: 4.99,
    link: uuidv4(),
  },
];
